### ISSUE TITLE
Will this increase the user's data flow ？

### ISSUE THREAD

**Issue by ponyfe** [wingjay/BlurImageView#1]
I like this view very much ,but I have some problems too.
As there have an extra image to be downloaded ,will this increase data flow usage?How this view resolve this problem ?
I am wondering is there anyway for the client to detect the image info and download as scream ? Not the service return two set images?

**Comment by wingjay** [comment]
Cool, These are good questions!

Q1: As there have an extra image to be downloaded ,will this increase data flow usage?How this view resolve this problem?
A1: Yes, this way of loading pic do increase data flow usage. For BlurImageView now, it doesn't do anything about this. But Let's be clear of the condition when this view is being used. 
First, if you decide to use this view, that means you have harsh demand for high quality and big size image, which takes normally 200KB - 400KB (this range depends on yourself, like [this one](https://github.com/wingjay/BlurImageView/blob/master/app/src/main/res/drawable/medium_nm_1.jpeg)). For 2G user (network speed ranges from 10KB/s - 25KB/s) This loading needs 15s+, For 3G user (100KB/s - 200KB/s), still needs 1.5s - 2s. So you can negotiation with yourself based on the best user experience.
Second, the size of small pic which will be loaded firstly often is very low like [this one](https://github.com/wingjay/BlurImageView/blob/master/app/src/main/res/drawable/medium_sm_1.jpeg), Its size is 0.8KB, It's very fast and low-costing to load this pic, But it can really improve user experience especially when user has bad network or the real image has very big size.

So, you should choose to use BlurImageView based on condition.

Q2:  is there anyway for the client to detect the image info and download as scream ? Not the service return two set images?
A2: It's a good question. Actually I'm also learn the Progressive loading image. Recommend this article to you [Faster Photos in Facebook for iOS](https://code.facebook.com/posts/857662304298232/faster-photos-in-facebook-for-ios/). This way only needs to load once, but it's kinds of difficulty to use.

Thx for your question.

**Comment by ponyfe** [comment]
@wingjay Thanks for your explanation , I read that post , but still can't find the best way to achieve this good feature in android . I am still learning too . :smile:
