### ISSUE TITLE
Specifying ScaleType does not have any effect on the Image.

### ISSUE THREAD

**Issue by iAviatorJose** [wingjay/BlurImageView#2]
I specified the scaleType in xml and
also tried it programmatically. None of the trial worked.

@wingjay do you know anything why this may be happening

**Comment by wingjay** [comment]
In consideration of that the small image has very small size, So I limit this scaleType to only be ScaleType.FIT_CENTER.
See here: https://github.com/wingjay/BlurImageView/blob/master/blurimageviewlib/src/main/java/com/wingjay/blurimageviewlib/BlurImageView.java#L62

https://github.com/wingjay/BlurImageView/blob/master/blurimageviewlib/src/main/java/com/wingjay/blurimageviewlib/BlurImageView.java#L43
