### ISSUE TITLE
Scale_type is not working

### ISSUE THREAD

**Issue by branemk** [wingjay/BlurImageView#3]
I have imageview set like this

<com.wingjay.blurimageviewlib.BlurImageView

```
android:layout_width="match_parent"
android:layout_height="match_parent"
android:scaleType="fitXY"

android:src="@drawable/grey"

/>
```

but Image view look like this https://goo.gl/photos/QaF3F8xCe6CfNLRF7 . I tried changing scale programmatically , same thing. 

I downloaded your project and changed scale in blur class to fitxy , same thing . 

What can be the problem .

**Comment by wingjay** [comment]
Sorry for late answer.

the BlurImageView is actually not a ImageView, see here https://github.com/wingjay/BlurImageView/blob/master/blurimageviewlib/src/main/java/com/wingjay/blurimageviewlib/BlurImageView.java#L33

And I'll add a public function to allow to set its scaleType.

Thanks.
